### ISSUE TITLE
TODO Soon-ish

### ISSUE THREAD

**Issue by CraigRoss95** [CraigRoss95/Website2022#17]
- [ ] Add link to article
- [ ] Update DJ image
- [ ] Have portfolio buttons scroll to top of page
- [ ] Add support for multiple images on a post/article
- [ ] Change up dog Easter egg lines
- [ ] Have alternating templates work the same on horizontal and vertical smart phones (it works on vertical now)
- [ ] Finish README

**Comment by Rxazz1** [comment]
Tolls ish
